# -*- mode: python ; coding: utf-8 -*-
# Generated by UnifyPy 2.0

block_cipher = None

a = Analysis(
    ['/Users/junsen/Desktop/workspace/py-xiaozhi/main.py'],
    pathex=[],
    binaries=[],
    datas=[('models', 'models'), ('scripts', 'scripts'), ('src', 'src'), ('libs', 'libs'), ('assets', 'assets')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='py-xiaozhi',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    icon='assets/icon.png',
)

coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='py-xiaozhi')

app = BUNDLE(
    coll,
    name='py-xiaozhi.app',
    icon='assets/icon.png',
    bundle_identifier='com.py-xiaozhi.app',
    info_plist={'CFBundleName': 'py-xiaozhi', 'CFBundleDisplayName': 'Xiao Zhi', 'CFBundleExecutable': 'py-xiaozhi', 'CFBundlePackageType': 'APPL', 'CFBundleVersion': '2.0.4', 'CFBundleShortVersionString': '2.0.4', 'CFBundleIdentifier': 'com.py-xiaozhi.app', 'NSPrincipalClass': 'NSApplication', 'CFBundleDevelopmentRegion': 'en', 'LSHasLocalizedDisplayName': True, 'NSHighResolutionCapable': True, 'LSMinimumSystemVersion': '10.13', 'LSApplicationCategoryType': 'public.app-category.productivity', 'NSHumanReadableCopyright': '© 2024 Company. All rights reserved.', 'LSUIElement': False, 'NSSupportsAutomaticGraphicsSwitching': True, 'NSMicrophoneUsageDescription': 'This app requires access to the microphone to enable recording functionality.', 'NSCameraUsageDescription': 'This app requires access to the camera to take photos or record videos.', 'NSSpeechRecognitionUsageDescription': 'This app requires the use of speech recognition to understand voice commands.'},
)
